spring.application.name=viajes

# conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/viajes
spring.datasource.username=root
spring.datasource.password=JYjik7RTX*



# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de tamaño de archivos subidos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
