spring.application.name=viajes

# Conexión a MySQL (variables desde .env)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración de Vipps
vipps.client-id=${VIPPS_CLIENT_ID}
vipps.client-secret=${VIPPS_CLIENT_SECRET}
vipps.subscription-key=${VIPPS_SUBSCRIPTION_KEY}
vipps.msn=${VIPPS_MSN}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de tamaño de archivos subidos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
